language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements/development.txt
script:
  - pycodestyle .