language: python
python:
  - "3.5"
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install -r requirements/development.txt
notifications:
  slack: myspace-kaoru:24x83GHaRJRGYWzvcC1s23SP
env:
  - DJANGO_VERSION=3.0.7